### your site title here

title: Siba를 닮은 '나', DevDoggy

baseurl: /
sass:
    style: compressed


# Tracker
analytics: UA-83979019-1

disqus: sindevdoggy-disqus-com


categoies : ["node","java","Spring","javascript","html,css","jekyll","web","php"]
# 카테고리 테스트!


exclude:
- README.md

include:
- _pages
