### your site title here

title: Siba를 닮은 '나', DevDoggy

baseurl: /
sass:
    style: compressed


# Tracker
analytics: UA-83979019-1
disqus: sindevdoggy-disqus-com

exclude:
- README.md

include:
- _pages
